### ISSUE TITLE
README contains broken link

### ISSUE THREAD

**Issue by doggy8088** [msyrus/vscode-go-doc#1]
These two links are broken:

- [gogetdoc](https://github.com/msyrus/vscode-go-doc/blob/master/github.com/zmb3/gogetdoc)
- [godoc](https://github.com/msyrus/vscode-go-doc/blob/master/golang.org/x/tools/cmd/godoc)

I can't use this extension as well.

![image](https://user-images.githubusercontent.com/88981/88409164-23dcfe80-ce07-11ea-8569-d0871ec20e4a.png)

**Comment by msyrus** [comment]
You need to install `gogetdoc`.

One easy solution can be adding `gogetdoc` in your `$GOBIN` by running
```
go get github.com/zmb3/gogetdoc
```

**Comment by doggy8088** [comment]
Hi @msyrus , can you put some usage sample in the README? I still don't know how to use it.

**Comment by msyrus** [comment]
I have updated the extension to install gogetdoc into `GOPATH` if missing. I hope this will ease its usage.

Just put the cursor on any of the go struct or function and run command `Go Doc: Get Definition` from command palette you should see the definition of the symbol into the `Go Doc` Output channel at bellow.
